jwt:
  secret: a6e21884876f43819523c31033fa697e

spring:
  datasource:
    url: jdbc:h2:mem:santander
    driverClassName: org.h2.Driver
    username: sa
    password: password
  flyway:
    table: articulos_web_flyway_schema_history
    locations: classpath:/test/db/migration
  #Propiedades para las conexiones a la base de datos
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: false

org:
  hibernate:
    envers:
      audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
      audit_strategy_validity_store_revend_timestamp: true

repo_pdf: c:\repoFiles\